/*
 * generated by Xtext
 */
package com.br.refactoring.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends com.br.refactoring.xtext.AbstractDslRuntimeModule {

}
